CREATE DATABASE IF NOT EXISTS chat2db_mysql_obj_014;
USE chat2db_mysql_obj_014;

DROP TABLE IF EXISTS ts_partitioned_orders;
DROP TABLE IF EXISTS ts_orders_migrated;
DROP TABLE IF EXISTS ts_orders;

CREATE TABLESPACE chat2db_ts_general ADD DATAFILE 'chat2db_ts_general.ibd' ENGINE = InnoDB;
CREATE TABLESPACE chat2db_ts_empty ADD DATAFILE 'chat2db_ts_empty.ibd' FILE_BLOCK_SIZE = 8192 ENGINE = InnoDB;

CREATE TABLE ts_orders (
  id BIGINT NOT NULL PRIMARY KEY,
  note VARCHAR(128)
) ENGINE = InnoDB TABLESPACE chat2db_ts_general;

CREATE TABLE ts_orders_migrated (
  id BIGINT NOT NULL PRIMARY KEY,
  note VARCHAR(128)
) ENGINE = InnoDB;

ALTER TABLE ts_orders_migrated TABLESPACE chat2db_ts_general;

SELECT TABLESPACE_NAME, ENGINE, TABLESPACE_TYPE
FROM INFORMATION_SCHEMA.TABLESPACES
WHERE TABLESPACE_NAME IN ('chat2db_ts_general', 'chat2db_ts_empty')
ORDER BY TABLESPACE_NAME;

SELECT FILE_NAME, TABLESPACE_NAME
FROM INFORMATION_SCHEMA.FILES
WHERE TABLESPACE_NAME IN ('chat2db_ts_general', 'chat2db_ts_empty')
ORDER BY TABLESPACE_NAME, FILE_NAME;

SELECT REPLACE(I.NAME, '/', '.') AS OBJECT_NAME
FROM INFORMATION_SCHEMA.INNODB_TABLES I
JOIN INFORMATION_SCHEMA.INNODB_TABLESPACES S ON S.SPACE = I.SPACE
WHERE S.NAME = 'chat2db_ts_general'
ORDER BY OBJECT_NAME;
