CREATE DATABASE IF NOT EXISTS chat2db_mysql_obj_014;
USE chat2db_mysql_obj_014;

DROP TABLE IF EXISTS ts_partitioned_orders;
DROP TABLE IF EXISTS ts_orders_migrated;
DROP TABLE IF EXISTS ts_orders;

CREATE TABLESPACE chat2db_ts_general ADD DATAFILE 'chat2db_ts_general.ibd' ENGINE = InnoDB;
CREATE TABLESPACE chat2db_ts_empty ADD DATAFILE 'chat2db_ts_empty.ibd' FILE_BLOCK_SIZE = 8192 ENGINE = InnoDB;

CREATE TABLE ts_orders (
  id BIGINT NOT NULL PRIMARY KEY,
  note VARCHAR(128)
) ENGINE = InnoDB TABLESPACE chat2db_ts_general;

CREATE TABLE ts_orders_migrated (
  id BIGINT NOT NULL PRIMARY KEY,
  note VARCHAR(128)
) ENGINE = InnoDB;

ALTER TABLE ts_orders_migrated TABLESPACE chat2db_ts_general;

CREATE TABLE ts_partitioned_orders (
  id BIGINT NOT NULL,
  created_year INT NOT NULL,
  note VARCHAR(128),
  PRIMARY KEY (id, created_year)
) ENGINE = InnoDB
PARTITION BY RANGE (created_year) (
  PARTITION p2025 VALUES LESS THAN (2026) TABLESPACE chat2db_ts_general,
  PARTITION pmax VALUES LESS THAN MAXVALUE
);

SELECT NAME, ENGINE, FILE_BLOCK_SIZE
FROM INFORMATION_SCHEMA.TABLESPACES
WHERE NAME IN ('chat2db_ts_general', 'chat2db_ts_empty')
ORDER BY NAME;

SELECT FILE_NAME, TABLESPACE_NAME
FROM INFORMATION_SCHEMA.FILES
WHERE TABLESPACE_NAME IN ('chat2db_ts_general', 'chat2db_ts_empty')
ORDER BY TABLESPACE_NAME, FILE_NAME;

SELECT TABLE_SCHEMA, TABLE_NAME, TABLESPACE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'chat2db_mysql_obj_014'
  AND TABLESPACE_NAME = 'chat2db_ts_general'
ORDER BY TABLE_NAME;

SELECT TABLE_SCHEMA, TABLE_NAME, PARTITION_NAME, TABLESPACE_NAME
FROM INFORMATION_SCHEMA.PARTITIONS
WHERE TABLE_SCHEMA = 'chat2db_mysql_obj_014'
  AND TABLESPACE_NAME = 'chat2db_ts_general'
ORDER BY TABLE_NAME, PARTITION_NAME;
